name: Pull Request

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  echo_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello World
        run: echo "Hello World"
