name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: assignmentdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Logitech@135#
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Packer
        uses: hashicorp/setup-packer@main
        with:
          packer-version: "latest"

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      - name: Initialize Packer
        run: packer fmt packer/custom-image.pkr.hcl

      - name: Validate Packer Template
        run: packer validate packer/custom-image.pkr.hcl
