name: CI Tests

on:
  pull_request:
    branches: ["main"]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PostgreSQL for Linux/macOS/Windows
        uses: ikalnytskyi/action-setup-postgres@v5
        with:
          username: ${{ secrets.DB_USER }}
          password: ${{ secrets.DB_PASSWORD }}
          database: ${{ secrets.DB_NAME }}
          port: 5432

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      - name: Maven Tests
        run: mvn test
