name: Packer-CI

on:
  push:
    branches: ["main"]

jobs:
  packer-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PostgreSQL for Linux/macOS/Windows
        uses: ikalnytskyi/action-setup-postgres@v5
        with:
          username: ${{ secrets.DB_USER }}
          password: ${{ secrets.DB_PASSWORD }}
          database: ${{ secrets.DB_NAME }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      - name: Test with Maven
        run: mvn test

      - name: Authenticate GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use GCP CLI
        run: gcloud info

      - name: Initialize Packer
        run: packer init packer/custom-image.pkr.hcl

      - name: Validate Packer Template
        run: packer validate packer/custom-image.pkr.hcl

      - name: Build Packer Template
        run: packer build packer/custom-image.pkr.hcl
