name: Packer-CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  POSTGRES_DB: ${{ secrets.DB_NAME }}
  POSTGRES_USER: ${{ secrets.DB_USER }}
  POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  packer-ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: POSTGRES_DB
          POSTGRES_USER: POSTGRES_USER
          POSTGRES_PASSWORD: POSTGRES_PASSWORD
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      - name: Authenticate GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use GCP CLI
        run: gcloud info

      - name: Initialize Packer
        run: packer init packer/custom-image.pkr.hcl

      - name: Validate Packer Template
        run: packer validate packer/custom-image.pkr.hcl

      - name: Build Packer Template
        run: packer build packer/custom-image.pkr.hcl
